spring.application.name=spring-boot
spring.datasource.url=jdbc:mysql://localhost:3306/bank_db
spring.datasource.username=root
spring.datasource.password=myPassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=xxx123@gmail.com
spring.mail.password=xxxxabc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
app.jwt-secret=H0wY7g53T4Bw6czR51DnEvpBXgmuioc3
app.jwt-expiration=86400000
logging.level.org.springframework.security=DEBUG
